from app import db, Card


card = Card(suit='AS', value=1)
card2 = Card(suit='2S', value=2)
card3 = Card(suit='3S', value=3)
card4 = Card(suit='4S', value=4)
card5 = Card(suit='5S', value=5)
card6 = Card(suit='6S', value=6)
card7 = Card(suit='7S', value=7)
card8 = Card(suit='8S', value=8)
card9 = Card(suit='9S', value=9)
card10 = Card(suit='10S', value=10)
card11 = Card(suit='JS', value=10)
card12 = Card(suit='QS', value=10)
card13 = Card(suit='KS', value=10)
card14 = Card(suit='AD', value=1)
card15 = Card(suit='2D', value=2)
card16 = Card(suit='3D', value=3)
card17 = Card(suit='4D', value=4)
card18 = Card(suit='5D', value=5)
card19 = Card(suit='6D', value=6)
card20 = Card(suit='7D', value=7)
card21 = Card(suit='8D', value=8)
card22 = Card(suit='9D', value=9)
card23 = Card(suit='10D', value=10)
card24 = Card(suit='JD', value=10)
card25 = Card(suit='QD', value=10)
card26 = Card(suit='KD', value=10)
card27 = Card(suit='AH', value=1)
card28 = Card(suit='2H', value=2)
card29 = Card(suit='3H', value=3)
card30 = Card(suit='4H', value=4)
card31 = Card(suit='5H', value=5)
card32 = Card(suit='6H', value=6)
card33 = Card(suit='7H', value=7)
card34 = Card(suit='8H', value=8)
card35 = Card(suit='9H', value=9)
card36 = Card(suit='10H', value=10)
card37 = Card(suit='JH', value=10)
card38 = Card(suit='QH', value=10)
card39 = Card(suit='KH', value=10)
card40 = Card(suit='AC', value=1)
card41 = Card(suit='2C', value=2)
card42 = Card(suit='3C', value=3)
card43 = Card(suit='4C', value=4)
card44 = Card(suit='5C', value=5)
card45 = Card(suit='6C', value=6)
card46 = Card(suit='7C', value=7)
card47 = Card(suit='8C', value=8)
card48 = Card(suit='9C', value=9)
card49 = Card(suit='10C', value=10)
card50 = Card(suit='JC', value=10)
card51 = Card(suit='QC', value=10)
card52 = Card(suit='KC', value=10)
db.session.add(card)
db.session.add(card2)
db.session.add(card3)
db.session.add(card4)
db.session.add(card5)
db.session.add(card6)
db.session.add(card7)
db.session.add(card8)
db.session.add(card9)
db.session.add(card10)
db.session.add(card11)
db.session.add(card12)
db.session.add(card13)
db.session.add(card14)
db.session.add(card15)
db.session.add(card16)
db.session.add(card17)
db.session.add(card18)
db.session.add(card19)
db.session.add(card20)
db.session.add(card21)
db.session.add(card22)
db.session.add(card23)
db.session.add(card24)
db.session.add(card25)
db.session.add(card26)
db.session.add(card27)
db.session.add(card28)
db.session.add(card29)
db.session.add(card30)
db.session.add(card31)
db.session.add(card32)
db.session.add(card33)
db.session.add(card34)
db.session.add(card35)
db.session.add(card36)
db.session.add(card37)
db.session.add(card38)
db.session.add(card39)
db.session.add(card40)
db.session.add(card41)
db.session.add(card42)
db.session.add(card43)
db.session.add(card44)
db.session.add(card45)
db.session.add(card46)
db.session.add(card47)
db.session.add(card48)
db.session.add(card49)
db.session.add(card50)
db.session.add(card51)
db.session.add(card52)


db.session.commit()
